# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
        
    - name: Install dependencies
      run: |
          go get .
          go get github.com/gorilla/mux 
          go get github.com/json-iterator/go 
          go get github.com/sashabaranov/go-openai 
          go get github.com/xen0n/go-workwx 
          go get gopkg.in/yaml.v3 

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
